version: '2'
services:
  web:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - .:/app
    - /app/server/node_modules
    - /app/client/node_modules
    - /app/client/dist
    links:
    - mongo

  mongo:
    image: mongo:3.7
